// Built-in preset generator: reads presets/*.json (app-exported presets) and
// emits scripts/svelte/builtin-presets.generated.ts so they ship bundled with
// the app. Run via `pnpm presets:build`; also runs before `pnpm build`/`pnpm dev`.
//
// Authoring loop: tune in the app -> Export -> drop the .json into presets/ ->
// rerun this. See presets/README.md.
import { readdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import prettier from "@pathtx/prettier";

const root = dirname(fileURLToPath(import.meta.url));
const presetsDir = join(root, "presets");
const outFile = join(root, "scripts", "svelte", "builtin-presets.generated.ts");

// Keep in sync with PRESET_VERSION / APP_VERSION in presets.ts / const.ts.
const PRESET_VERSION = 1;
const APP_VERSION = 0.6;

const entries = (await readdir(presetsDir))
  .filter((f) => f.toLowerCase().endsWith(".json"))
  .sort(); // filename order -> deterministic output

const presets = [];
for (const file of entries) {
  const raw = await readFile(join(presetsDir, file), "utf8");
  let p;
  try {
    p = JSON.parse(raw);
  } catch (err) {
    throw new Error(`presets/${file}: invalid JSON — ${err.message}`);
  }
  // Validate like importPresetFile() does in presets.ts.
  if (typeof p !== "object" || p === null || typeof p.settings !== "object") {
    throw new Error(
      `presets/${file}: not a valid preset (missing a "settings" object)`,
    );
  }
  const name =
    typeof p.name === "string" && p.name
      ? p.name
      : file.replace(/\.json$/i, "");
  presets.push({
    name,
    version: typeof p.version === "number" ? p.version : PRESET_VERSION,
    appVersion: typeof p.appVersion === "number" ? p.appVersion : APP_VERSION,
    settings: p.settings,
    curves: p.curves ?? {},
  });
}

const banner =
  "// AUTO-GENERATED by gen-presets.mjs from presets/*.json — DO NOT EDIT.\n" +
  "// Regenerate with `pnpm presets:build` (also runs before build/dev).\n";

const body =
  banner +
  'import type { Preset } from "./presets.js";\n\n' +
  `export const GENERATED_BUILTINS: Preset[] = ${JSON.stringify(presets, null, 2)};\n`;

// Format with the repo's prettier fork so the committed file is stable and a
// later `pnpm format` (or a build-time regen) never leaves a dirty tree.
const formatted = await prettier.format(body, { parser: "typescript" });

await writeFile(outFile, formatted);
console.log(
  `Generated ${entries.length} built-in preset(s) -> scripts/svelte/builtin-presets.generated.ts`,
);
